name: ENANA

on: [push]

jobs:
  ci:
  on: ubuntu-latest

  steps:
      - uses: actions/checkout@v2
      - name: PHPUnit Tests
        uses: php-actions/phpunit@v2
        env:
          TEST_NAME: enanaTest
        with:
          configuration: test/phpunit.xml
          args: --coverage-text

